In [7]:
"""Build a df in pandas"""
import pandas as pd

def test_run():
    start_date='2010-01-22'
    end_date='2010-01-26'
    dates=pd.date_range(start_date,end_date)
    
    # create an empty dataframe
    df1=pd.DataFrame(index=dates)
    
    #read SPY data into a temp dataframe
    dfSPY = pd.read_csv("data/SPY.csv", index_col="Date", 
                        parse_date=True, usecols=['Date', 'Adj Close'],
                       na_values=['nan'])
    
    # Join the two dataframes using DataFrame.join()
    df1=df1.join(dfSPY)
    print df1
    #print dfSPY
    
if __name__ == '__main__':
    test_run()

                    Date  Open  High  Low  Close  Volume  Adj Close
2010-01-22 00:00:00  NaN   NaN   NaN  NaN    NaN     NaN        NaN
2010-01-23 00:00:00  NaN   NaN   NaN  NaN    NaN     NaN        NaN
2010-01-24 00:00:00  NaN   NaN   NaN  NaN    NaN     NaN        NaN
2010-01-25 00:00:00  NaN   NaN   NaN  NaN    NaN     NaN        NaN
2010-01-26 00:00:00  NaN   NaN   NaN  NaN    NaN     NaN        NaN
            Date    Open    High     Low   Close     Volume  Adj Close
0     2012-09-12  144.39  144.55  143.90  144.39   87607000     144.39
1     2012-09-11  143.60  144.37  143.56  143.91   88647200     143.91
2     2012-09-10  144.19  144.44  143.46  143.51   86458500     143.51
3     2012-09-07  144.01  144.39  143.88  144.33  107272100     144.33
4     2012-09-06  141.76  143.78  141.75  143.77  158272500     143.77
5     2012-09-05  141.09  141.47  140.63  140.91  100660300     140.91
6     2012-09-04  141.04  141.46  140.13  141.03  120226200     141.03
7     2012-08-31  141.29  141.82  140.36  141.16  151970400     141.16
8     2012-08-30  140.90  140.94  140.19  140.49   96589900     140.49
9     2012-08-29  141.52  141.89  141.12  141.51   65421300     141.51
10    2012-08-28  141.18  141.84  140.97  141.40   75689600     141.40
11    2012-08-27  141.89  142.08  141.34  141.54   68785900     141.54
12    2012-08-24  140.31  141.83  140.22  141.51   99481200     141.51
13    2012-08-23  141.47  141.48  140.44  140.66  111466400     140.66
14    2012-08-22  141.40  142.05  141.07  141.82  133243500     141.82
15    2012-08-21  142.54  143.09  141.45  141.76  105581100     141.76
16    2012-08-20  141.98  142.22  141.59  142.19   78255700     142.19
17    2012-08-17  142.23  142.30  141.86  142.18   90813700     142.18
18    2012-08-16  141.15  142.16  140.80  141.99  112014200     141.99
19    2012-08-15  140.64  141.19  140.55  140.95   71085900     140.95
20    2012-08-14  141.29  141.38  140.37  140.79  102379400     140.79
21    2012-08-13  140.60  140.84  140.04  140.77   79426900     140.77
22    2012-08-10  140.04  140.89  139.81  140.84   99792700     140.84
23    2012-08-09  140.29  140.89  140.15  140.61   90291700     140.61
24    2012-08-08  139.85  140.65  139.81  140.49   89754700     140.49
25    2012-08-07  140.18  140.92  140.03  140.32  109545100     140.32
26    2012-08-06  139.72  140.17  139.56  139.62   86326200     139.62
27    2012-08-03  138.56  139.64  136.68  139.35  157825000     139.35
28    2012-08-02  136.55  137.57  135.58  136.64  199556600     136.64
29    2012-08-01  138.70  138.73  137.40  137.59  138293800     137.59
...          ...     ...     ...     ...     ...        ...        ...
3145  2000-03-14  139.28  140.09  136.16  136.63    8263900     110.02
3146  2000-03-13  136.69  140.47  135.69  138.59   10540500     111.60
3147  2000-03-10  140.19  142.00  139.53  140.13    7924600     112.84
3148  2000-03-09  137.25  140.88  136.13  140.88    5500900     113.44
3149  2000-03-08  136.47  137.84  135.03  136.88   11808500     110.22
3150  2000-03-07  140.00  140.16  135.22  137.05   20062000     110.36
3151  2000-03-06  140.81  141.34  138.75  139.75   11967100     112.53
3152  2000-03-03  140.44  141.72  139.72  141.13   12770300     113.64
3153  2000-03-02  138.69  139.13  137.34  138.53    7600200     111.55
3154  2000-03-01  137.63  139.00  137.22  138.44    6868000     111.48
3155  2000-02-29  136.06  137.44  135.75  137.44    8242500     110.67
3156  2000-02-28  133.38  136.69  132.72  136.13   13397800     109.62
3157  2000-02-25  135.19  136.72  133.13  133.33   10559900     107.36
3158  2000-02-24  136.69  137.03  133.09  133.81   17375000     107.75
3159  2000-02-23  135.63  137.47  134.50  136.56   12119000     109.96
3160  2000-02-22  135.19  136.34  133.53  134.97   16415400     108.68
3161  2000-02-18  138.88  138.88  134.63  135.31    9409200     108.95
3162  2000-02-17  140.44  140.44  138.22  138.28    7584200     111.35
3163  2000-02-16  140.38  140.94  138.80  139.00    8845400     111.93
3164  2000-02-15  139.25  141.22  137.80  141.08   11078300     113.60
3165  2000-02-14  139.78  139.78  138.31  139.50    8528800     112.33
3166  2000-02-11  141.84  141.94  138.03  138.69    9849800     111.68
3167  2000-02-10  141.63  142.56  140.88  141.56    6690600     113.99
3168  2000-02-09  144.47  144.47  141.27  141.28    8511500     113.76
3169  2000-02-08  143.97  144.56  143.63  144.31    4936400     116.20
3170  2000-02-07  142.56  142.78  141.44  142.38    5845800     114.65
3171  2000-02-04  143.19  144.00  142.13  142.59    4925400     114.82
3172  2000-02-03  140.88  143.25  140.00  143.19    7997500     115.30
3173  2000-02-02  141.28  142.25  140.38  141.06    6205900     113.58
3174  2000-02-01  139.75  141.69  138.53  140.94    8419900     113.49

[3175 rows x 7 columns]